// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/shop-designs/BoldMarket.tsx": () => import("../components/mockups/shop-designs/BoldMarket.tsx"),
  "./components/mockups/shop-designs/ClassicPremium.tsx": () => import("../components/mockups/shop-designs/ClassicPremium.tsx"),
  "./components/mockups/shop-designs/LuxuryDark.tsx": () => import("../components/mockups/shop-designs/LuxuryDark.tsx"),
  "./components/mockups/shop-designs/ModernMinimal.tsx": () => import("../components/mockups/shop-designs/ModernMinimal.tsx")
};
